**<font color='red'>Change the name from assignment_lastname to include YOUR last name</font>**. This will make sure that the assignment doesn't get overwritten when you do a ```git pull upstream master``` in class. 

# Homework 3B - the coding portion

## Due: Friday, October 16, by 5pm

Skills: numpy, basic python 

Turn in instructions:
1. Before turning in your notebook, make sure you save it first using the floppy disk save icon or File -> save.
2. Open a new terminal ```New -> Terminal```, cd into the directory where you worked on this homework. For most of you that should be ~/PreMAP2020/homework/
3. To turn in your assignment, you need to “git push” your assignment to your github using the following commands. You’ll need to be inside the PreMAP2020 directory for this to work. (Not in your home directory.)
```
git add *
git commit -m “<Include a message inside quotes: i.e. Finished HW 3B>”
git push
```

Always start with your import statement! You will only need the package `numpy` for today's homework

In [151]:
#We're going to be using numpy in this homework, so we need to import it first.
import numpy as np

#The next command makes sure that when I try to display images they show to the notebook screen
%matplotlib inline 

### The exercises in this coding assignment will be based on the article you read for Homework 3A. You can find a link to the article [here](https://astrobites.org/2018/07/18/best-exoplanet-destinations-for-mountain-climbers/).

**Before you get started:**
Remember that you have many tools to help you out with coding! First, please reference the notebooks we've been working through in class. Great coders copy their old code ALL THE TIME, it is a great resource! You should also make Google your best friend for code questions. Don't hesitate to google your questions. Lastly, you should get familiar with the built in documentation for python and python packages such as numpy. You can access help pages by typing the function name, followed by a ? in a coding cell and then executing it.

**1)**
Use the `print` command to print the title of the astrobites article to the screen.

In [152]:
print('Best exoplanet destinations for mountain climbers')

Best exoplanet destinations for mountain climbers


Using Figure 1 from the paper as a reference, we're going to use Python to do some calculations for us:

In [153]:
#IGNORE THIS CELL - I'm just using it to display Figure 1 from the paper.
from IPython.display import Image
from IPython.display import display
#lc = Image(filename='/astro/users/mlazz/PreMAP2019/homework/data/exomountain_trainsit.png') 
#display(lc)

**2)**
Create a variable called `delta_sphere` and a variable called `delta_block`. Assuming that the bottom of the graph is 0, choose a reasonable value for both variables between 0 and 1. 

In [154]:
delta_sphere = 0.4
delta_block = 0.2

**3)** How much larger is `delta_sphere` than `delta_block`?

In [155]:
print ("It is",delta_sphere/delta_block, "times bigger")

It is 2.0 times bigger


**4)**
From the paper, we know that the transit depth, $\delta$ is related to the cross-sectional area of the planet, A, and the radius of the host star, R, using the equation: $\delta = \frac{A}{\pi R^{2}}$. 

Using your value for `delta_sphere` above, if the cross-sectional area of the planet is 0.5, what is the radius of the host star? Print the radius to the screen. *Hint: the value of $\pi$ is built into `numpy`, you can use it by typing `np.pi`.*

In [156]:
A = 0.5
R = np.sqrt(A/np.pi*(delta_sphere))
print(R)

0.252313252202016


**5)**
Let's say you had a whole bunch of these observations and wanted to calculate the radii of a bunch of stars. Create a numpy array called `areas` that contains 10 cross-sectional areas evenly spaced out between 0.1 and 1 (including both 0.1 and 1). Print your `areas` array to the screen. Calculate the radius of the host star for each planet with an area in the `areas` array. Create an array called `radii` that contains the radius of each of thse host stars and print it to the screen.

In [157]:
areas = np.arange(.1,1.1,.1)

In [158]:
print(areas)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [159]:
radii = np.sqrt((areas)/(np.pi*(delta_sphere)))
print(radii)

[0.28209479 0.39894228 0.48860251 0.56418958 0.63078313 0.6909883
 0.74635267 0.79788456 0.84628438 0.89206206]


**6)** Let's do some math with these numbers, just to test out some of the handy calculations we can do with python and the numpy package. Raise every value of the `radii` array to the 2nd power. Trick - do this two different ways! You will soon learn that there are always multiple ways to do something with Python, and usually more than one good way to do it! You can raise an array to a power using just normal python math operators (+, -, $*$, $**$, etc.) and with the built in `numpy` function `np.power`. Please show that you can do it both ways in the empty cell below.

Helpful hint, if you aren't sure what arguments the `np.power` function takes, read its help docs by executing the cell below.

In [160]:
np.power(radii,2)

array([0.07957747, 0.15915494, 0.23873241, 0.31830989, 0.39788736,
       0.47746483, 0.5570423 , 0.63661977, 0.71619724, 0.79577472])

In [161]:
radii**2

array([0.07957747, 0.15915494, 0.23873241, 0.31830989, 0.39788736,
       0.47746483, 0.5570423 , 0.63661977, 0.71619724, 0.79577472])

**7)** Sum up the radius of each host star in the `radii` array.

In [162]:
np.sum(radii)

6.338184256454815

**8)** Subtract 0.5 from each value in the `radii` array.

In [163]:
np.subtract(radii,.5)

array([-0.21790521, -0.10105772, -0.01139749,  0.06418958,  0.13078313,
        0.1909883 ,  0.24635267,  0.29788456,  0.34628438,  0.39206206])

**9)** Divide each value of the radii array by 2.

In [164]:
radii/2

array([0.1410474 , 0.19947114, 0.24430126, 0.28209479, 0.31539157,
       0.34549415, 0.37317633, 0.39894228, 0.42314219, 0.44603103])

**10)** Let's create a new array of star radii called `new_radii`. The `new_radii` array should contain all multiples of 3 between 0 and 999, including 999. Print `new_radii` to the screen.

In [165]:
new_radii = np.arange(0,1001,3)
print (new_radii)

[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51
  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105
 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159
 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213
 216 219 222 225 228 231 234 237 240 243 246 249 252 255 258 261 264 267
 270 273 276 279 282 285 288 291 294 297 300 303 306 309 312 315 318 321
 324 327 330 333 336 339 342 345 348 351 354 357 360 363 366 369 372 375
 378 381 384 387 390 393 396 399 402 405 408 411 414 417 420 423 426 429
 432 435 438 441 444 447 450 453 456 459 462 465 468 471 474 477 480 483
 486 489 492 495 498 501 504 507 510 513 516 519 522 525 528 531 534 537
 540 543 546 549 552 555 558 561 564 567 570 573 576 579 582 585 588 591
 594 597 600 603 606 609 612 615 618 621 624 627 630 633 636 639 642 645
 648 651 654 657 660 663 666 669 672 675 678 681 684 687 690 693 696 699
 702 705 708 711 714 717 720 723 726 729 732 735 73

**11)** Calculate the cross sectional area of the planet for each of the host stars in the `new_radii` array. Save these values in an array called `new_areas`.

In [166]:
new_areas = np.pi*((new_radii)**2)

**12)** You might notice that when you print out `new_areas` that the values are listed in scientific notation. This is a useful feature of Python, especially when working with big numbers like we do in astronomy. Print the 5th element of the `new_areas` array to the screen. *Hint: remember that Python indexes starting with 0.

In [167]:
print(new_areas[6])

1017.8760197630929


**13)** What is the sum of the cross sectional areas of all of the planets in the `new_areas` array?

In [168]:
np.sum(new_areas)

349588925.2266227

**14)** What is the sum of the radii of all of the stars in the `new_radii` array with a radius of greater than 400?

In [169]:
largerThanRadii = new_radii > 400
#intiall tried to this via an if then statment then realised that was too messy so googled it and ralsied i was being dumb :p
np.sum(largerThanRadii)

200

**15)** How many of the values in `new_radii` are even? Use Exercise 5 (putting it all together) from the `numpy` lesson as a reference.

In [170]:
evenRadii = np.where(new_radii%2 == 0)
print(evenRadii)

(array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332]),)


In [171]:
#IGNORE THIS CELL - just displaying Figure 2
#bumpiness = #Image(filename='/astro/users/mlazz/PreMAP2019/homework/data/bumpiness_fig2.png') 
#display(bumpiness)

**16)** Define a variable `r_star` with a value of 0.1 that defines the 0.1 solar radius M-dwarf star used as a reference in this paper. Create an array called `transit_scatter` that contains 100 values between 0.2 and 1.4 describing the transit scatter of 100 fictional planets. 

Use the equation printed on the figure to determine the bumpiness of each of these planets. Save the bumpiness of each planet into an array called `bumpiness`. Print `bumpiness` to the screen.

In [172]:
# not sure how to define R_star so did two versions
r_star1 = .1
mdwarfRadius= 0.203
r_star2 = .1*mdwarfRadius
transmit_scatter = np.arange(0.2,1.4,.012)

bumpiness1 = 624.24 + ((r_star1**2)*174636.7*transmit_scatter)
bumpiness2 = 624.24 + ((r_star2**2)*174636.7*transmit_scatter)
#then up here i print both versions
print ("bumpiness equation version 1:", bumpiness1)
print ("bumpiness eqution version 2:", bumpiness2)

bumpiness equation version 1: [ 973.5134    994.469804 1015.426208 1036.382612 1057.339016 1078.29542
 1099.251824 1120.208228 1141.164632 1162.121036 1183.07744  1204.033844
 1224.990248 1245.946652 1266.903056 1287.85946  1308.815864 1329.772268
 1350.728672 1371.685076 1392.64148  1413.597884 1434.554288 1455.510692
 1476.467096 1497.4235   1518.379904 1539.336308 1560.292712 1581.249116
 1602.20552  1623.161924 1644.118328 1665.074732 1686.031136 1706.98754
 1727.943944 1748.900348 1769.856752 1790.813156 1811.76956  1832.725964
 1853.682368 1874.638772 1895.595176 1916.55158  1937.507984 1958.464388
 1979.420792 2000.377196 2021.3336   2042.290004 2063.246408 2084.202812
 2105.159216 2126.11562  2147.072024 2168.028428 2188.984832 2209.941236
 2230.89764  2251.854044 2272.810448 2293.766852 2314.723256 2335.67966
 2356.636064 2377.592468 2398.548872 2419.505276 2440.46168  2461.418084
 2482.374488 2503.330892 2524.287296 2545.2437   2566.200104 2587.156508
 2608.112912 2629.069316

**17)** The height of Mt. Everest is 8848 meters. What would the transit depth of a planet need to be in order for its `bumpiness` to be equal to the height of Mt. Everest?

In [173]:
#4.70906?

**18)** What is the mean bumpiness of your planets? What is the standard deviation of the bumpiness? What is the median? *Hint: there are functions in numpy for all of these google it if you don't remember!*

In [174]:
mean1 = np.mean(bumpiness1)
mean2 = np.mean(bumpiness2)
#since I had two definition for bumpiness
print ("mean 1:",mean1,"mean 2:", mean2)

mean 1: 2010.8553980000015 mean 2: 681.3810339361821


In [175]:
median1 = np.median(bumpiness1)
median2 = np.median(bumpiness2)
#since I had two definition for bumpiness
print ("median 1:",median1,"median 2:", median2)

median 1: 2010.8553980000013 median 2: 681.3810339361821


In [176]:
stdDev1 = np.std(bumpiness1)
stdDev2 = np.std(bumpiness2)
print ("Standard deviation on Bumpiness1:",median1,"Standard deviation on Bumpiness1:", median2)

Standard deviation on Bumpiness1: 2010.8553980000013 Standard deviation on Bumpiness1: 681.3810339361821


**19)** Let's say, more realistically, we changed the radius of the star in our bumpiness diagram to the radius of the Sun, R = 1 $R_{*}$. Using the value of the transit depth scatter from Figure 2 for both the wet and dry Earth, what would be the bumpiness in meters of the wet and the dry Earth?

**20)** How do these new bumpiness measurements compare to Mt. Everest? 

Write your answer here in this markdown cell:
